"""
safe-pip watch mode v1.1
Installs a pip shim that intercepts `pip install` in all terminals:
  - CMD: pip.bat shim in Scripts/ and shim dir
  - PowerShell: function pip { ... } in all PS profiles
  - Any terminal: shim dir added to PATH before real pip
"""

from __future__ import annotations

import os
import platform
import shutil
import stat
import sys
from pathlib import Path
from typing import Optional

import click
from rich.console import Console

console = Console()

IS_WINDOWS = platform.system() == "Windows"

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

def _shim_dir() -> Path:
    if IS_WINDOWS:
        return Path(os.environ.get("APPDATA", Path.home() / "AppData" / "Roaming")) / "safe-pip" / "shims"
    return Path.home() / ".local" / "share" / "safe-pip" / "shims"


def _find_safe_pip_exe() -> str:
    exe = shutil.which("safe-pip")
    if exe:
        return exe
    scripts = Path(sys.executable).parent
    for name in ("safe-pip", "safe-pip.exe"):
        p = scripts / name
        if p.exists():
            return str(p)
    return "safe-pip"


def _find_real_pip() -> str:
    """Find the real pip executable, skipping any shim directory."""
    shim = str(_shim_dir()).lower()
    for candidate in ("pip", "pip3"):
        found = shutil.which(candidate)
        if found and shim not in found.lower():
            return found
    scripts = Path(sys.executable).parent
    for name in ("pip.exe", "pip", "pip3.exe", "pip3"):
        p = scripts / name
        if p.exists() and shim not in str(p).lower():
            return str(p)
    return "pip"


# ---------------------------------------------------------------------------
# Shim content generators
# ---------------------------------------------------------------------------

def _windows_shim_content(safe_pip_exe: str, real_pip: str) -> str:
    return f"""@echo off
REM safe-pip shim — intercepts pip install and routes through safe-pip scan
REM Generated by: safe-pip watch enable
REM Remove with:  safe-pip watch disable
REM
REM Emergency bypass (CMD):        set SAFE_PIP_BYPASS=1 && pip install X && set SAFE_PIP_BYPASS=
REM Emergency bypass (PowerShell): $env:SAFE_PIP_BYPASS=1; pip install X; $env:SAFE_PIP_BYPASS=""

REM Only intercept "pip install ..." — forward everything else immediately
if /i not "%~1"=="install" goto :real_pip

REM --- Emergency bypass ---
if not "%SAFE_PIP_BYPASS%"=="" (
    echo [safe-pip] SAFE_PIP_BYPASS set -- skipping scan
    goto :real_pip
)

REM --- Bypass conditions ---
if /i "%~2"=="-e" goto :real_pip
if /i "%~2"=="--editable" goto :real_pip
if /i "%~2"=="-r" goto :real_pip
if /i "%~2"=="--requirement" goto :real_pip

echo %* | findstr /i "safe-pip safe_pip safe-pip-scanner" >nul 2>&1
if not errorlevel 1 goto :real_pip

if not exist "{safe_pip_exe}" goto :real_pip

echo %2 | findstr /r "^[.]" >nul 2>&1
if not errorlevel 1 goto :real_pip
echo %2 | findstr /i ".whl .tar.gz .zip" >nul 2>&1
if not errorlevel 1 goto :real_pip

REM --- Run safe-pip scan (called at top level — not inside if block) ---
"{safe_pip_exe}" install %2 %3 %4 %5 %6 %7 %8 %9
set SAFEPIP_RC=%ERRORLEVEL%

if %SAFEPIP_RC% neq 0 (
    echo.
    echo [safe-pip] Blocked ^(exit %SAFEPIP_RC%^). Run: safe-pip doctor
    echo [safe-pip] Bypass: set SAFE_PIP_BYPASS=1 ^&^& pip install X ^&^& set SAFE_PIP_BYPASS=
    exit /b %SAFEPIP_RC%
)

REM --- Scan passed: run real pip to actually install ---
:real_pip
{real_pip} %*
exit /b %ERRORLEVEL%
"""


def _unix_shim_content(safe_pip_exe: str, real_pip: str) -> str:
    return f"""#!/bin/sh
# safe-pip shim — intercepts pip install and routes through safe-pip scan
# Generated by: safe-pip watch enable
# Remove with:  safe-pip watch disable

# Only intercept install subcommand
if [ "$1" != "install" ]; then
    exec {real_pip} "$@"
fi

# Emergency bypass
if [ -n "$SAFE_PIP_BYPASS" ]; then
    echo "[safe-pip] SAFE_PIP_BYPASS set -- skipping scan"
    exec {real_pip} "$@"
fi

# Bypass: editable / requirements file / local path
case "$2" in
    -e|--editable|-r|--requirement) exec {real_pip} "$@" ;;
    *.whl|*.tar.gz|*.zip|./*|/*)    exec {real_pip} "$@" ;;
esac

# Run safe-pip scan
"{safe_pip_exe}" install "$@"
SAFEPIP_RC=$?
if [ "$SAFEPIP_RC" -ne 0 ]; then
    echo ""
    echo "[safe-pip] Installation blocked (exit code $SAFEPIP_RC)."
    echo "[safe-pip] Emergency bypass: SAFE_PIP_BYPASS=1 pip install <package>"
    exit $SAFEPIP_RC
fi

# Scan passed: run real pip
exec {real_pip} "$@"
"""


_PS_ALIAS_TEMPLATE = """# >>> safe-pip watch >>>
# Auto-generated by: safe-pip watch enable
# Remove with:       safe-pip watch disable
function pip {{
    if ($args.Count -gt 0 -and $args[0] -eq "install") {{
        # Run safe-pip scan first
        & "{safe_pip_exe}" install ($args | Select-Object -Skip 1)
        $rc = $LASTEXITCODE
        if ($rc -ne 0) {{
            Write-Host ""
            Write-Host "[safe-pip] Installation blocked (exit code $rc)." -ForegroundColor Red
            Write-Host "[safe-pip] Emergency bypass: `$env:SAFE_PIP_BYPASS=1; pip install <package>; `$env:SAFE_PIP_BYPASS=''" -ForegroundColor Yellow
            return
        }}
        # Scan passed: run real pip
        & "{real_pip}" @args
    }} else {{
        & "{real_pip}" @args
    }}
}}
# <<< safe-pip watch <<<
"""


# ---------------------------------------------------------------------------
# Windows: PATH management
# ---------------------------------------------------------------------------

def _windows_get_user_path() -> str:
    try:
        import winreg
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_READ)
        val, _ = winreg.QueryValueEx(key, "Path")
        winreg.CloseKey(key)
        return val
    except Exception:
        return os.environ.get("PATH", "")


def _windows_set_user_path(new_path: str) -> None:
    try:
        import winreg
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0, winreg.KEY_SET_VALUE)
        winreg.SetValueEx(key, "Path", 0, winreg.REG_EXPAND_SZ, new_path)
        winreg.CloseKey(key)
        import ctypes
        ctypes.windll.user32.SendMessageW(0xFFFF, 0x001A, 0, "Environment")
    except Exception:
        pass


def _windows_add_to_path(directory: str) -> bool:
    current = _windows_get_user_path()
    dirs = [d for d in current.split(";") if d.strip()]
    if directory in dirs:
        return False
    dirs.insert(0, directory)
    _windows_set_user_path(";".join(dirs))
    return True


def _windows_remove_from_path(directory: str) -> bool:
    current = _windows_get_user_path()
    dirs = [d for d in current.split(";") if d.strip() and d != directory]
    _windows_set_user_path(";".join(dirs))
    return True


def _windows_fix_pathext() -> bool:
    """Ensure .BAT resolves before .EXE so pip.bat intercepts pip.exe."""
    try:
        import winreg
        key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0,
                             winreg.KEY_READ | winreg.KEY_SET_VALUE)
        try:
            val, _ = winreg.QueryValueEx(key, "PATHEXT")
        except FileNotFoundError:
            val = os.environ.get("PATHEXT", ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC")
        exts = [e.upper() for e in val.split(";") if e.strip()]
        if ".BAT" in exts and ".EXE" in exts:
            if exts.index(".BAT") > exts.index(".EXE"):
                exts.remove(".BAT")
                exe_idx = exts.index(".EXE")
                exts.insert(exe_idx, ".BAT")
                new_val = ";".join(exts)
                winreg.SetValueEx(key, "PATHEXT", 0, winreg.REG_SZ, new_val)
                winreg.CloseKey(key)
                return True
        winreg.CloseKey(key)
    except Exception:
        pass
    return False


# ---------------------------------------------------------------------------
# PowerShell profiles
# ---------------------------------------------------------------------------

def _find_powershell_profiles() -> list[Path]:
    if not IS_WINDOWS:
        return []
    docs = Path.home() / "Documents"
    profiles = []
    for ps_dir in ("WindowsPowerShell", "PowerShell"):
        for profile_name in ("Microsoft.PowerShell_profile.ps1", "profile.ps1"):
            profiles.append(docs / ps_dir / profile_name)
    return profiles


def _write_ps_alias(safe_pip_exe: str, real_pip: str) -> list[Path]:
    snippet = _PS_ALIAS_TEMPLATE.format(safe_pip_exe=safe_pip_exe, real_pip=real_pip)
    written = []
    for profile in _find_powershell_profiles():
        profile.parent.mkdir(parents=True, exist_ok=True)
        existing = profile.read_text(encoding="utf-8") if profile.exists() else ""
        if "safe-pip watch" in existing:
            continue
        profile.write_text(existing + "\n" + snippet, encoding="utf-8")
        written.append(profile)
    return written


def _remove_ps_alias() -> int:
    removed = 0
    for profile in _find_powershell_profiles():
        if not profile.exists():
            continue
        content = profile.read_text(encoding="utf-8")
        if "safe-pip watch" not in content:
            continue
        lines = content.splitlines()
        out, inside = [], False
        for line in lines:
            if ">>> safe-pip watch >>>" in line:
                inside = True
            if not inside:
                out.append(line)
            if "<<< safe-pip watch <<<" in line:
                inside = False
        profile.write_text("\n".join(out), encoding="utf-8")
        removed += 1
    return removed


# ---------------------------------------------------------------------------
# CMD shims
# ---------------------------------------------------------------------------

def _write_cmd_shim(target: Path, safe_pip_exe: str, real_pip: str) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_windows_shim_content(safe_pip_exe, real_pip), encoding="utf-8")


def _remove_cmd_shim(target: Path) -> bool:
    if not target.exists():
        return False
    content = target.read_text(encoding="utf-8")
    if "safe-pip shim" not in content:
        return False
    target.unlink()
    return True


def _cmd_shim_locations(real_pip: str) -> list[Path]:
    """Return all pip.bat locations to install/remove."""
    locations = []
    # shim dir (for PATH-based interception)
    locations.append(_shim_dir() / "pip.bat")
    # beside each pip.exe in PATH
    for name in ("pip.exe", "pip3.exe"):
        found = shutil.which(name)
        if found:
            p = Path(found).parent / (Path(found).stem + ".bat")
            if p not in locations:
                locations.append(p)
    # beside real pip
    rp = Path(real_pip)
    if rp.exists():
        for stem in ("pip", "pip3"):
            p = rp.parent / f"{stem}.bat"
            if p not in locations:
                locations.append(p)
    return locations


# ---------------------------------------------------------------------------
# Unix PATH management
# ---------------------------------------------------------------------------

def _unix_rc_files() -> list[Path]:
    home = Path.home()
    candidates = [
        home / ".bashrc", home / ".bash_profile", home / ".zshrc",
        home / ".profile", home / ".config" / "fish" / "config.fish",
    ]
    return [p for p in candidates if p.exists()]


def _unix_add_to_path(directory: str) -> bool:
    marker = f'# safe-pip: PATH={directory}'
    export = f'export PATH="{directory}:$PATH"'
    for rc in _unix_rc_files():
        content = rc.read_text(encoding="utf-8")
        if marker in content:
            return False
        rc.write_text(content + f"\n{marker}\n{export}\n", encoding="utf-8")
    return True


def _unix_remove_from_path(directory: str) -> bool:
    removed = False
    marker = f'# safe-pip: PATH={directory}'
    for rc in _unix_rc_files():
        content = rc.read_text(encoding="utf-8")
        if marker not in content:
            continue
        lines = [l for l in content.splitlines()
                 if marker not in l and directory not in l]
        rc.write_text("\n".join(lines), encoding="utf-8")
        removed = True
    return removed


# ---------------------------------------------------------------------------
# Enable / Disable
# ---------------------------------------------------------------------------

def enable(force: bool = False) -> dict:
    """Install shims in all terminal environments."""
    safe_pip_exe = _find_safe_pip_exe()
    real_pip     = _find_real_pip()
    shim_d       = _shim_dir()
    shim_d.mkdir(parents=True, exist_ok=True)

    result = {
        "safe_pip_exe": safe_pip_exe,
        "real_pip":     real_pip,
        "shim_dir":     str(shim_d),
        "cmd_shims":    [],
        "ps_profiles":  [],
        "path_updated": False,
        "pathext_fixed": False,
    }

    if IS_WINDOWS:
        # CMD shims
        for loc in _cmd_shim_locations(real_pip):
            _write_cmd_shim(loc, safe_pip_exe, real_pip)
            result["cmd_shims"].append(str(loc))

        # PowerShell alias
        written = _write_ps_alias(safe_pip_exe, real_pip)
        result["ps_profiles"] = [str(p) for p in written]

        # PATH: shim dir first
        result["path_updated"] = _windows_add_to_path(str(shim_d))

        # PATHEXT: .BAT before .EXE
        result["pathext_fixed"] = _windows_fix_pathext()
    else:
        # Unix: write shim + add to PATH
        shim_path = shim_d / "pip"
        shim_path.write_text(_unix_shim_content(safe_pip_exe, real_pip), encoding="utf-8")
        shim_path.chmod(shim_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        result["cmd_shims"].append(str(shim_path))
        result["path_updated"] = _unix_add_to_path(str(shim_d))

    return result


def disable() -> dict:
    """Remove all shims from all terminal environments."""
    shim_d  = _shim_dir()
    result  = {"cmd_removed": 0, "ps_removed": 0, "path_removed": False}

    if IS_WINDOWS:
        for loc in _cmd_shim_locations(_find_real_pip()):
            if _remove_cmd_shim(loc):
                result["cmd_removed"] += 1
        result["ps_removed"]   = _remove_ps_alias()
        result["path_removed"] = _windows_remove_from_path(str(shim_d))
        # Clean up shim dir
        if shim_d.exists():
            try:
                shutil.rmtree(shim_d)
            except Exception:
                pass
    else:
        shim_path = shim_d / "pip"
        if shim_path.exists():
            shim_path.unlink()
            result["cmd_removed"] = 1
        result["path_removed"] = _unix_remove_from_path(str(shim_d))

    return result


def status() -> dict:
    shim_d    = _shim_dir()
    shim_file = shim_d / ("pip.bat" if IS_WINDOWS else "pip")
    on_path   = str(shim_d).lower() in os.environ.get("PATH", "").lower()
    return {
        "active":    shim_file.exists() and on_path,
        "shim_file": str(shim_file),
        "shim_exists": shim_file.exists(),
        "on_path":   on_path,
        "platform":  "Windows" if IS_WINDOWS else platform.system(),
    }


# ---------------------------------------------------------------------------
# CLI commands (added to main CLI in cli.py)
# ---------------------------------------------------------------------------

@click.group("watch")
def watch_cmd():
    """Manage pip interception across all terminal environments."""
    pass


@watch_cmd.command("enable")
def watch_enable():
    """Install pip shim in CMD, PowerShell, and PATH."""
    console.print("\n[bold]safe-pip watch[/bold] — enabling\n")
    r = enable()

    console.print(f"  [green]✓[/green] Shim installed → {r['shim_dir']}")
    console.print(f"  [green]✓[/green] Real pip       → {r['real_pip']}")
    if r.get("path_updated"):
        console.print("  [green]✓[/green] Shim directory added to your PATH.")
    if r.get("pathext_fixed"):
        console.print("  [green]✓[/green] PATHEXT updated — .BAT now resolves before .EXE.")
    if r.get("ps_profiles"):
        console.print(f"  [green]✓[/green] PowerShell alias written to {len(r['ps_profiles'])} profile(s):")
        for p in r["ps_profiles"]:
            console.print(f"     {p}")
    if r.get("cmd_shims"):
        console.print(f"\n  CMD coverage:")
        for s in r["cmd_shims"]:
            console.print(f"  [green]✓[/green] pip.bat installed → {s}")

    console.print("\n  [yellow]⚠[/yellow]  Open a new terminal for changes to take effect.")
    console.print("\n  Every [bold]pip install X[/bold] will be scanned.")
    console.print("  Disable at any time with: [bold]safe-pip watch disable[/bold]\n")


@watch_cmd.command("disable")
def watch_disable():
    """Remove pip shim from all terminals."""
    console.print("\n[bold]safe-pip watch[/bold] — disabling\n")
    r = disable()

    if r["cmd_removed"]:
        console.print(f"  [green]✓[/green] CMD shim(s) removed from {r['cmd_removed']} location(s).")
    else:
        console.print("  No shim found (already disabled).")
    if r.get("ps_removed"):
        console.print(f"  [green]✓[/green] PowerShell alias removed from {r['ps_removed']} profile(s).")
    if r.get("path_removed"):
        console.print("  [green]✓[/green] Shim directory removed from PATH.")

    console.print("\n  Watch mode is now off. pip install commands run normally.")
    console.print("  [yellow]⚠[/yellow]  Open a new terminal to apply the PATH change.\n")


@watch_cmd.command("status")
def watch_status():
    """Show watch mode status."""
    s = status()
    shim_exists = s["shim_exists"]
    on_path     = s["on_path"]

    # If shim exists but not on PATH, the user is in the same terminal
    # they ran `watch enable` in — PATH hasn't refreshed yet.
    if shim_exists and not on_path:
        state = "[yellow]PENDING[/yellow] — open a new terminal to activate"
    elif s["active"]:
        state = "[green]ACTIVE[/green]"
    else:
        state = "[dim]INACTIVE[/dim]"

    console.print(f"\n  [bold]Watch mode:[/bold] {state}")
    console.print(f"  Platform   : {s['platform']}")
    console.print(f"  Shim file  : {s['shim_file']}")
    console.print(f"  Shim exists: {'yes' if shim_exists else 'no'}")
    console.print(f"  On PATH    : {'yes' if on_path else 'no'}")

    if shim_exists and not on_path:
        console.print()
        console.print("  [yellow]ℹ[/yellow]  Shim is installed but this terminal was opened before")
        console.print("     [yellow]safe-pip watch enable[/yellow] ran. Open a [bold]new[/bold] terminal")
        console.print("     and run [bold]pip install X[/bold] — it will be intercepted.")
    elif not shim_exists:
        console.print()
        console.print("  Run [bold]safe-pip watch enable[/bold] to activate.")
    console.print()
